### ISSUE TITLE
Error: X-Total-Count in header must be of type int64: ""

### ISSUE THREAD

**Issue by fnxpt** [goharbor/go-client#10]
I checked #6 and Im still facing the same issue with version 0.24.3.

**Comment by fnxpt** [comment]
I found the issue, there was a issue with the endpoint, if you have the same issue, be sure you have the complete api path

**Comment by vvavad** [comment]
I am using the Harbor demo setup(https://demo.goharbor.io/) and facing this error. Any way this can be fixed?

**Comment by YaozhongZhang** [comment]
> I am using the Harbor demo setup(https://demo.goharbor.io/) and facing this error. Any way this can be fixed?

@vvavad  the URL shoud be "https://demo.goharbor.io/api/v2.0/"
