### ISSUE TITLE
Vulnerability additions content type

### ISSUE THREAD

**Issue by fnxpt** [goharbor/go-client#11]
When call the vulnerabilities additions content type we receive a error message
json: cannot unmarshal object into Go value of type string
The api shows that the content type of this object is a string, but in fact it needs to be a structure.

**Comment by ralgozino** [comment]
Hi @fnxpt!
Do you happen to know if there's any workaround to this issue while it gets fixed on harbor's side?

**Comment by fnxpt** [comment]
I don’t think it’s possible because swagger is saying that the output is a string and not a structure, this leads to a parsing error. The fix should come from the source of the swagger documentation

**Comment by ralgozino** [comment]
thank you for the quick answer @fnxpt 🙏

**Comment by fnxpt** [comment]
Added a PR to add the missing schema, already tested against a fork and it works correctly, we just need to regenerate the client as soon as we have the PR merged
