### ISSUE TITLE
REST Api or SDK to download Image

### ISSUE THREAD

**Issue by cbsundaram** [goharbor/go-client#21]
Referring to swagger https://demo.goharbor.io/devcenter-api-2.0 is there any REST api or SDK method which can download the image artifact (in .tar format) for a given project and repository in Harbor? 

We tried with Docker pull and save for this. However, we need an API or SDK method to download the image programmatically without invoking docker commands.

**Comment by Vad1mo** [comment]
this doesnt exist but you can build one yourself easily,  with https://github.com/google/go-containerregistry
